// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzo3Z3U2tCSpH_RTjEek5tEFdw_GxwuLk',
    appId: '1:291698977867:android:8188b776b4008ef78ff1ce',
    messagingSenderId: '291698977867',
    projectId: 'mementales-app',
    storageBucket: 'mementales-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA149YJ5h1K52YPj-UUah8oqAssq4jPV_I',
    appId: '1:291698977867:ios:78dc47334a1231b58ff1ce',
    messagingSenderId: '291698977867',
    projectId: 'mementales-app',
    storageBucket: 'mementales-app.firebasestorage.app',
    androidClientId: '291698977867-l2ep3j2s90qu4cg1eiiubvpbv42b6pff.apps.googleusercontent.com',
    iosClientId: '291698977867-529que1abmoi5o0tdd0559tb66b2vroh.apps.googleusercontent.com',
    iosBundleId: 'com.example.mementales',
  );

}